-- ============================================================
-- Esquema de la base de datos — Sistema de Membresía CFNJ
-- Pegar completo en Supabase: SQL Editor → New query → Run
-- ============================================================

create table if not exists public.miembros (
  id bigint generated by default as identity primary key,
  "nombres" text not null default '',
  "ci" text default '',
  "fechaNacimiento" text default '',
  "lugarNacimiento" text default '',
  "estadoCivil" text default '',
  "correo" text default '',
  "telefono" text default '',
  "direccion" text default '',
  "ocupacion" text default '',
  "profesion" text default '',
  "esposo" text default '',
  "hijos" text default '',
  "padres" text default '',
  "viveConPadres" text default '',
  "viveConEsposoHijos" text default '',
  "recibioCristo" text default '',
  "bautizo" text default '',
  "tiempoConfraternidad" text default '',
  "funcion" text default '',
  "foto" text,
  "estado" text default 'Activo',
  "renovado" boolean default true,
  "seedKey" text,
  "fechaRegistro" timestamptz default now()
);

-- Seguridad: solo usuarios con sesión iniciada pueden ver y modificar
alter table public.miembros enable row level security;

drop policy if exists "miembros_select" on public.miembros;
drop policy if exists "miembros_insert" on public.miembros;
drop policy if exists "miembros_update" on public.miembros;
drop policy if exists "miembros_delete" on public.miembros;

create policy "miembros_select" on public.miembros
  for select to authenticated using (true);
create policy "miembros_insert" on public.miembros
  for insert to authenticated with check (true);
create policy "miembros_update" on public.miembros
  for update to authenticated using (true);
create policy "miembros_delete" on public.miembros
  for delete to authenticated using (true);

-- ============================================================
-- Registro con código de invitación: bloquea en el servidor la
-- creación de cuentas que no traigan el código correcto.
-- Si cambias el código, cámbialo aquí Y en config-nube.js.
-- ============================================================
create or replace function public.validar_codigo_invitacion()
returns trigger
language plpgsql
security definer
as $$
begin
  if coalesce(new.raw_user_meta_data->>'codigo', '') <> 'CCNJ-2026' then
    raise exception 'Codigo de invitacion incorrecto';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_codigo_invitacion on auth.users;
create trigger trg_codigo_invitacion
  before insert on auth.users
  for each row execute function public.validar_codigo_invitacion();
